#! /bin/bash

# stop script when an error occurs
set -e

psql -q -c "CREATE USER consumer SUPERUSER"
echo "Created Postgres user 'consumer'"

psql -q -c "CREATE DATABASE wib WITH OWNER consumer"
echo "Created Postgres database 'wib'"

echo "DATABASE_URL='postgres://consumer:@localhost:5432/wib'" > .env
echo "Created .env containing DATABASE_URL"