#! /bin/sh

# stop script when an error occurs
set -e

# import .env so we can access DB URL
. "./.env"

# psql $DATABASE_URL -q -f "./database/init.sql"
# echo "Populated database tables"

if [ -z "$DATABASE_NAME" ]
then
  echo "\$DATABASE_NAME is empty!"
else
  echo "Found \$DATABASE_NAME in .env"
  echo "Now executing database init file in psql..."
  psql $DATABASE_NAME -q -f "./database/init.sql"
  echo "Populated database tables"
fi